name: recipeapp_final
description: A new Flutter project.

publish_to: "none"

version: 2.1.0+3

environment:
  sdk: ">=3.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.15.6
  webview_flutter: ^3.0.4

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
